<?php

namespace Tests\Helpers;

use App\User;
use Laravel\Sanctum\Sanctum;

trait Authenticatable
{
    protected $testUser;

    protected $testUserCredentials = [
        'email' => 'john.doe@gmail.com',
        'password' => 'asdasd123'
    ];

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->testUser =  factory(User::class, 1)->create($this->testUserCredentials)->first();

        Sanctum::actingAs($this->testUser);
    }

    protected function testUser() : User
    {
        return $this->testUser;
    }
}